name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: npm install and npm run build
        run: |
          npm run build:ci
